
language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - psql -c 'create database muserpol_tests;' -U postgres
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --force

script:
  - vendor/bin/phpunit